name: Frontend Linting

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.eslintrc.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/frontend-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
